### ISSUE TITLE
Issues with using gridlayout with rmd file

### ISSUE THREAD

**Issue by natesheehan** [rstudio/gridlayout#11]
Hi! I am really excited to see this project, however I am having difficulties in setting up a gridlayout for a `rmd` file. Would you be able to provide a reprex of a working example?

**Comment by nstrayer** [comment]
Here's an example taken from `inst/demo_apps/rmarkdown_demo`:

__`grid_markdown.Rmd`__
````
---
title: "`gridlayout` in Rmarkdown"
author: "Nick Strayer"
date: "3/9/2021"
output:
  html_document:
    theme:
      version: 5
---

```{r setup, include=FALSE}
library(gridlayout)

knitr::opts_chunk$set(echo = TRUE)

use_gridlayout_rmd()
```

```{css echo=FALSE}
.section {
  outline: 2px solid silver;
  padding: 10px;
}
```


# main {.no-header}

Main content!


```{r}
sessionInfo()
```

```{gridlayout}
|      |        |         |
|------|--------|---------|
|      |200px   |1fr      |
|170px |header  |header   |
|1fr   |sidebar |main     |
|120px |footer  |footer   |
```


# Sidebar

Here is some content for the sidebar

# Footer

Anything you want could go in the footer.

````

Renders to: 
![image](https://user-images.githubusercontent.com/6764693/183466581-7ca717ae-05b5-4f75-aa86-29b66df7d288.png)

**Comment by nstrayer** [comment]
Looking at it now I do see that the "Using with Rmd" article is a bit messed up. I'll fix that. Thanks for pointing it out

**Comment by nstrayer** [comment]
Updated the article in https://github.com/rstudio/gridlayout/commit/9869487df905ead3ad21c5192602ce1189b33c7f to better show the exact Rmd structure you need to get things working

**Comment by nstrayer** [comment]
Closing this due to having a better example on the site now. Feel free to reopen it if you think things could be clearer!
