### ISSUE TITLE
Documentation references mystery `show_layout` function

### ISSUE THREAD

**Issue by natesheehan** [rstudio/gridlayout#12]
The documentation on this page https://rstudio.github.io/gridlayout/articles/defining-a-layout.html for the "The table array" section includes a function called `show_layout` which is not part of the `gridlayout` package.

**Comment by Tom271** [comment]
The function is not part of the package as you say, it is defined on the [top of this page](https://rstudio.github.io/gridlayout/articles/defining-a-layout.html ), namely: 
`library(gridlayout)

# Print the layout without showing mobile layouts
show_layout <- function(layout) {
  print(layout, show_alternates = FALSE)
}`

I also just got caught by this, not sure how the documentation could be rephrased to make that clearer?
