### ISSUE TITLE
Automatic number of columns

### ISSUE THREAD

**Issue by Nithador** [rstudio/gridlayout#21]
I stumbled across this example of having automatic number of columns depending on the width of the window [here](https://css-tricks.com/books/greatest-css-tricks/flexible-grids/)

Is something like this possible with gridlayout in R?

**Comment by gadenbuie** [comment]
I'm sure gridlayout could help you with this, but I can also tell you that `layout_column_wrap()` from [bslib](https://rstudio.github.io/bslib) uses this same concept. There's an example in [the column layouts article](https://rstudio.github.io/bslib/articles/column-layout/index.html#responsive-number-of-columns) that boils down to

```r
layout_column_wrap(
  width = "200px", 
  height = 300,
  card1, 
  card2,
  card3
)
```

where giving an absolute CSS unit to `width` is interpreted by `layout_column_wrap()` as layout these items, making each no smaller than `200px` and automatically laying out columns as described in the linked article.

**Comment by Nithador** [comment]
Thank You. I’ll try [bslib](https://rstudio.github.io/bslib). Closing this issue.
