### ISSUE TITLE
grid_panel overflow should be auto

### ISSUE THREAD

**Issue by wch** [rstudio/gridlayout#5]
With `overflow: scroll`, the scroll bars are always shown, even if they're not actually needed for the content. (On my Mac, I also have "Show scroll bars" set to Always.)

![image](https://user-images.githubusercontent.com/86978/118757941-a79f2600-b833-11eb-917c-50f730feaa25.png)

With `overflow: auto`, the scroll bars will appear only when needed.

**Comment by nstrayer** [comment]
Problem pushed off to `bslib::card()` as of #19
