### ISSUE TITLE
use of animate parameter in shiny sliderinput not accepted

### ISSUE THREAD

**Issue by apsteinmetz** [rstudio/gridlayout#8]
I don't know if this is a gridlayout issue but the same element parameters work in a non-gridlayout version of the shiny app.
The shiny ui editor does not provide the ability to add the `animate` parameter to `sliderInput` so I added it manually.  This code works in the original app:

```
 sliderInput("point","Number of points drawn",min=2,max=points,value=2,step=5,
                  animate=animationOptions(interval=points/60*2))
```
This code using gridlayout triggers a "non-numeric argument to binary operator" error.

```
  gridlayout::grid_panel_stack(
    area = "sidebar",
    item_alignment = "top",
    item_gap = "12px",
    shiny::sliderInput(
      inputId = "point",
      label = "Points Drawn",
      min = 1L,
      max = 6000L,
      value = 1L,
      animate=animationOptions(interval=points/60*2)
    ),

```
After I change the animate parameter simply to TRUE the app runs but ignores it.
```
  gridlayout::grid_panel_stack(
    area = "sidebar",
    item_alignment = "top",
    item_gap = "12px",
    shiny::sliderInput(
      inputId = "point",
      label = "Points Drawn",
      min = 1L,
      max = 6000L,
      value = 1L,
      animate=TRUE
    ),

```

Full code here: https://github.com/apsteinmetz/sve_beta_spiro.git

**Comment by nstrayer** [comment]
This is a `shinyuieditor` issue. Addressed and closed over there in https://github.com/rstudio/shinyuieditor/issues/29
